$('.slider').slick({
	infinite: true,
	lazyLoad: 'progressive',
	swipe: true,
	touchMove: true,
	draggable: true,
	initialSlide: 0,
 	slidesToShow: 1,
	slidesToScroll: 1,
	autoplay: true,
	autoplaySpeed: 4200,
	speed: 1200,
	cssEase: 'ease',
	pauseOnFocus: false,
	pauseOnHover: true,
	arrows: true,
	prevArrow: '<button type="button" class="slick-prev"><img class="slick-button-prev" src="img/arrow.png" alt="alt" />Previous</button>',
	nextArrow: '<button type="button" class="slick-next"><img class="slick-button-next" src="img/arrow.png" alt="alt" />Previous</button>',
	dots: false,
});
